# Generated by Django 4.1.2 on 2022-10-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='data',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='painel',
        ),
        migrations.RemoveField(
            model_name='queuespecial',
            name='data',
        ),
        migrations.RemoveField(
            model_name='queuespecial',
            name='painel',
        ),
    ]
